import { MigrationInterface, QueryRunner } from "typeorm";

export class AddOfferingsModule1769038417835 implements MigrationInterface {
    name = 'AddOfferingsModule1769038417835'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "geography" DROP CONSTRAINT "FK_geography_parent"`);
        await queryRunner.query(`ALTER TABLE "agent" DROP CONSTRAINT "FK_agent_geography"`);
        await queryRunner.query(`ALTER TABLE "agreement_party" DROP CONSTRAINT "FK_agreement_party_agreement"`);
        await queryRunner.query(`ALTER TABLE "agreement_party" DROP CONSTRAINT "FK_agreement_party_agent"`);
        await queryRunner.query(`ALTER TABLE "folder" DROP CONSTRAINT "FK_folder_parent"`);
        await queryRunner.query(`ALTER TABLE "file_upload" DROP CONSTRAINT "FK_file_upload_folder"`);
        await queryRunner.query(`ALTER TABLE "agreement" DROP CONSTRAINT "FK_agreement_parent"`);
        await queryRunner.query(`ALTER TABLE "agreement" DROP CONSTRAINT "FK_agreement_file"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_user_avatarFile"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_user_agent"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_user_relationshipAgreement"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_user_defaultLocale"`);
        await queryRunner.query(`ALTER TABLE "password_reset_token" DROP CONSTRAINT "FK_password_reset_token_user"`);
        await queryRunner.query(`ALTER TABLE "value_stream" DROP CONSTRAINT "FK_c22e3336d8df877dda668a93e8a"`);
        await queryRunner.query(`ALTER TABLE "value_stream" DROP CONSTRAINT "FK_value_stream_image"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_account_ownerAgent"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_account_value"`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" DROP CONSTRAINT "FK_ledger_transaction_fromAccount"`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" DROP CONSTRAINT "FK_ledger_transaction_toAccount"`);
        await queryRunner.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_channel_parent"`);
        await queryRunner.query(`ALTER TABLE "taxonomy" DROP CONSTRAINT "FK_4fb69b794e4809058d4ca3a2e57"`);
        await queryRunner.query(`ALTER TABLE "taxonomy" DROP CONSTRAINT "FK_taxonomy_image"`);
        await queryRunner.query(`ALTER TABLE "value_files" DROP CONSTRAINT "FK_value_files_value"`);
        await queryRunner.query(`ALTER TABLE "value_files" DROP CONSTRAINT "FK_value_files_file"`);
        await queryRunner.query(`ALTER TABLE "geography_closure" DROP CONSTRAINT "FK_geography_closure_ancestor"`);
        await queryRunner.query(`ALTER TABLE "geography_closure" DROP CONSTRAINT "FK_geography_closure_descendant"`);
        await queryRunner.query(`ALTER TABLE "folder_closure" DROP CONSTRAINT "FK_folder_closure_ancestor"`);
        await queryRunner.query(`ALTER TABLE "folder_closure" DROP CONSTRAINT "FK_folder_closure_descendant"`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" DROP CONSTRAINT "FK_agreement_closure_ancestor"`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" DROP CONSTRAINT "FK_agreement_closure_descendant"`);
        await queryRunner.query(`ALTER TABLE "channel_closure" DROP CONSTRAINT "FK_channel_closure_ancestor"`);
        await queryRunner.query(`ALTER TABLE "channel_closure" DROP CONSTRAINT "FK_channel_closure_descendant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_geography_code_parent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_coordinates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agent_geography"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_locale_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agreement_party_agreement"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agreement_party_agent"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_file_upload_folder"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_agentId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_password_reset_token_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_password_reset_token_tokenHash"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_account_ownerAgentId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_account_valueId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ledger_transaction_fromAccountId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ledger_transaction_toAccountId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ledger_transaction_timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ledger_transaction_verified"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_value_files_valueId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_value_files_fileId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_geography_closure_ancestor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_geography_closure_descendant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_folder_closure_ancestor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_folder_closure_descendant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agreement_closure_ancestor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_agreement_closure_descendant"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_channel_closure_ancestor"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_channel_closure_descendant"`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" DROP CONSTRAINT "CHK_ledger_transaction_different_accounts"`);
        await queryRunner.query(`CREATE TYPE "public"."offering_state_enum" AS ENUM('draft', 'live', 'archived')`);
        await queryRunner.query(`CREATE TABLE "offering" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(200) NOT NULL, "description" text, "purpose" character varying(500), "link" character varying(2048), "state" "public"."offering_state_enum" NOT NULL DEFAULT 'draft', "activeFrom" TIMESTAMP, "activeUntil" TIMESTAMP, "agentId" uuid NOT NULL, "valueStreamId" uuid NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d42d2720ff82f75aae518b9347c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "offering_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "offeringId" uuid NOT NULL, "valueId" uuid NOT NULL, "quantity" numeric(10,2) NOT NULL DEFAULT '1', "pricingFormula" character varying(500), "pricingLink" character varying(2048), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6f24dffc07f8d07b46593de57d2" UNIQUE ("offeringId", "valueId"), CONSTRAINT "PK_dab4a20c2ef399bc0a366821e81" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "offering_files" ("offeringId" uuid NOT NULL, "fileId" uuid NOT NULL, CONSTRAINT "PK_6115ffa24e7dd64e8ca9a0e6bb7" PRIMARY KEY ("offeringId", "fileId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_531bb15cc3c53b256ba573ac05" ON "offering_files" ("offeringId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4d17eb0772114ff72a7ed58d9d" ON "offering_files" ("fileId") `);
        await queryRunner.query(`ALTER TABLE "value_files" DROP COLUMN "position"`);
        await queryRunner.query(`ALTER TABLE "value_files" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TYPE "public"."file_storage_provider_enum" RENAME TO "file_storage_provider_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."file_upload_storageprovider_enum" AS ENUM('local', 's3')`);
        await queryRunner.query(`ALTER TABLE "file_upload" ALTER COLUMN "storageProvider" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_upload" ALTER COLUMN "storageProvider" TYPE "public"."file_upload_storageprovider_enum" USING "storageProvider"::"text"::"public"."file_upload_storageprovider_enum"`);
        await queryRunner.query(`ALTER TABLE "file_upload" ALTER COLUMN "storageProvider" SET DEFAULT 'local'`);
        await queryRunner.query(`DROP TYPE "public"."file_storage_provider_enum_old"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "UQ_user_agentId"`);
        await queryRunner.query(`CREATE INDEX "IDX_03f3269461e7b003dca6b1699f" ON "locale" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_e12875dfb3b1d92d7d7c5377e2" ON "user" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b61c694cacfab25533bd23d9ad" ON "user" ("agentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a4e53583f7a8ab7d01cded46a4" ON "password_reset_token" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_324e592c57094c9dcfa00ddf91" ON "password_reset_token" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_d1d0e4175c4251853024c24ff3" ON "value_files" ("valueId") `);
        await queryRunner.query(`CREATE INDEX "IDX_5ccf08bee106a423fcce33feec" ON "value_files" ("fileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7465429748c191ae44d8421269" ON "geography_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_d17903383ecacdb7a39ab91a79" ON "geography_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_073b49e13e4ebe5c294443a16b" ON "folder_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_fe732379b449e3dc89f52b8b44" ON "folder_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_cc76bd69d7789dd4ecb61db95b" ON "agreement_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_634acfdbad4946b437dc1d3d65" ON "agreement_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_3689646ea3533fa4b584a2185c" ON "channel_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_e5a503e5cbbd62cc42c05b3dfb" ON "channel_closure" ("id_descendant") `);
        await queryRunner.query(`ALTER TABLE "geography" ADD CONSTRAINT "FK_c67d70f484f1194d3586bbdcdcb" FOREIGN KEY ("parentId") REFERENCES "geography"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent" ADD CONSTRAINT "FK_92b8f3a4e5b1aaf7a8128e756a7" FOREIGN KEY ("geographyId") REFERENCES "geography"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_party" ADD CONSTRAINT "FK_6b1da075588819a6e5665188291" FOREIGN KEY ("agreementId") REFERENCES "agreement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_party" ADD CONSTRAINT "FK_5a75d372f3374aaea73bd1e3de4" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folder" ADD CONSTRAINT "FK_9ee3bd0f189fb242d488c0dfa39" FOREIGN KEY ("parentId") REFERENCES "folder"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_upload" ADD CONSTRAINT "FK_e518fe539e9b5ea0b0b35ffc82d" FOREIGN KEY ("folderId") REFERENCES "folder"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement" ADD CONSTRAINT "FK_b405575b2b53872d540f0487a63" FOREIGN KEY ("parentId") REFERENCES "agreement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement" ADD CONSTRAINT "FK_5354036afbc0e8c80bca5a39539" FOREIGN KEY ("fileId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_643734a7916743c1b226b9b1b32" FOREIGN KEY ("avatarFileId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_b61c694cacfab25533bd23d9add" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_a57aed940fb25c422f2774cd2b3" FOREIGN KEY ("relationshipAgreementId") REFERENCES "agreement"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_0d423777b801a88f0709c6be43e" FOREIGN KEY ("defaultLocaleId") REFERENCES "locale"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_token" ADD CONSTRAINT "FK_a4e53583f7a8ab7d01cded46a41" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_stream" ADD CONSTRAINT "FK_d37e3ffc041d9217905fa5d28ba" FOREIGN KEY ("imageId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_stream" ADD CONSTRAINT "FK_c22e3336d8df877dda668a93e8a" FOREIGN KEY ("parentId") REFERENCES "value_stream"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offering" ADD CONSTRAINT "FK_82eda015612fcb170f436545feb" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offering" ADD CONSTRAINT "FK_bc5b058bcf48bea21f3d172e61d" FOREIGN KEY ("valueStreamId") REFERENCES "value_stream"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offering_item" ADD CONSTRAINT "FK_9eee27210e398202f286bf15cf4" FOREIGN KEY ("offeringId") REFERENCES "offering"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offering_item" ADD CONSTRAINT "FK_a93ef368c6c18fc52388dccfe9d" FOREIGN KEY ("valueId") REFERENCES "value"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_d589c8f630adfbeee2faab2be85" FOREIGN KEY ("ownerAgentId") REFERENCES "agent"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_5694780140d82f9963d8ef3abd2" FOREIGN KEY ("valueId") REFERENCES "value"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" ADD CONSTRAINT "FK_0497f69c78a0440b477c7c3fea9" FOREIGN KEY ("fromAccountId") REFERENCES "account"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" ADD CONSTRAINT "FK_d7ce8d05cb211115e7947cb52e4" FOREIGN KEY ("toAccountId") REFERENCES "account"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_ef3b9e5596902ea33dd67a2a939" FOREIGN KEY ("parentId") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxonomy" ADD CONSTRAINT "FK_4d6d64d43b1003dde7cd7fd307d" FOREIGN KEY ("imageId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxonomy" ADD CONSTRAINT "FK_4fb69b794e4809058d4ca3a2e57" FOREIGN KEY ("parentId") REFERENCES "taxonomy"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offering_files" ADD CONSTRAINT "FK_531bb15cc3c53b256ba573ac05a" FOREIGN KEY ("offeringId") REFERENCES "offering"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "offering_files" ADD CONSTRAINT "FK_4d17eb0772114ff72a7ed58d9d5" FOREIGN KEY ("fileId") REFERENCES "file_upload"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "value_files" ADD CONSTRAINT "FK_d1d0e4175c4251853024c24ff30" FOREIGN KEY ("valueId") REFERENCES "value"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "value_files" ADD CONSTRAINT "FK_5ccf08bee106a423fcce33feec0" FOREIGN KEY ("fileId") REFERENCES "file_upload"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "geography_closure" ADD CONSTRAINT "FK_7465429748c191ae44d84212691" FOREIGN KEY ("id_ancestor") REFERENCES "geography"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geography_closure" ADD CONSTRAINT "FK_d17903383ecacdb7a39ab91a79a" FOREIGN KEY ("id_descendant") REFERENCES "geography"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folder_closure" ADD CONSTRAINT "FK_073b49e13e4ebe5c294443a16b4" FOREIGN KEY ("id_ancestor") REFERENCES "folder"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folder_closure" ADD CONSTRAINT "FK_fe732379b449e3dc89f52b8b441" FOREIGN KEY ("id_descendant") REFERENCES "folder"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" ADD CONSTRAINT "FK_cc76bd69d7789dd4ecb61db95bd" FOREIGN KEY ("id_ancestor") REFERENCES "agreement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" ADD CONSTRAINT "FK_634acfdbad4946b437dc1d3d659" FOREIGN KEY ("id_descendant") REFERENCES "agreement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_closure" ADD CONSTRAINT "FK_3689646ea3533fa4b584a2185ca" FOREIGN KEY ("id_ancestor") REFERENCES "channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_closure" ADD CONSTRAINT "FK_e5a503e5cbbd62cc42c05b3dfb3" FOREIGN KEY ("id_descendant") REFERENCES "channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "channel_closure" DROP CONSTRAINT "FK_e5a503e5cbbd62cc42c05b3dfb3"`);
        await queryRunner.query(`ALTER TABLE "channel_closure" DROP CONSTRAINT "FK_3689646ea3533fa4b584a2185ca"`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" DROP CONSTRAINT "FK_634acfdbad4946b437dc1d3d659"`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" DROP CONSTRAINT "FK_cc76bd69d7789dd4ecb61db95bd"`);
        await queryRunner.query(`ALTER TABLE "folder_closure" DROP CONSTRAINT "FK_fe732379b449e3dc89f52b8b441"`);
        await queryRunner.query(`ALTER TABLE "folder_closure" DROP CONSTRAINT "FK_073b49e13e4ebe5c294443a16b4"`);
        await queryRunner.query(`ALTER TABLE "geography_closure" DROP CONSTRAINT "FK_d17903383ecacdb7a39ab91a79a"`);
        await queryRunner.query(`ALTER TABLE "geography_closure" DROP CONSTRAINT "FK_7465429748c191ae44d84212691"`);
        await queryRunner.query(`ALTER TABLE "value_files" DROP CONSTRAINT "FK_5ccf08bee106a423fcce33feec0"`);
        await queryRunner.query(`ALTER TABLE "value_files" DROP CONSTRAINT "FK_d1d0e4175c4251853024c24ff30"`);
        await queryRunner.query(`ALTER TABLE "offering_files" DROP CONSTRAINT "FK_4d17eb0772114ff72a7ed58d9d5"`);
        await queryRunner.query(`ALTER TABLE "offering_files" DROP CONSTRAINT "FK_531bb15cc3c53b256ba573ac05a"`);
        await queryRunner.query(`ALTER TABLE "taxonomy" DROP CONSTRAINT "FK_4fb69b794e4809058d4ca3a2e57"`);
        await queryRunner.query(`ALTER TABLE "taxonomy" DROP CONSTRAINT "FK_4d6d64d43b1003dde7cd7fd307d"`);
        await queryRunner.query(`ALTER TABLE "channel" DROP CONSTRAINT "FK_ef3b9e5596902ea33dd67a2a939"`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" DROP CONSTRAINT "FK_d7ce8d05cb211115e7947cb52e4"`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" DROP CONSTRAINT "FK_0497f69c78a0440b477c7c3fea9"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_5694780140d82f9963d8ef3abd2"`);
        await queryRunner.query(`ALTER TABLE "account" DROP CONSTRAINT "FK_d589c8f630adfbeee2faab2be85"`);
        await queryRunner.query(`ALTER TABLE "offering_item" DROP CONSTRAINT "FK_a93ef368c6c18fc52388dccfe9d"`);
        await queryRunner.query(`ALTER TABLE "offering_item" DROP CONSTRAINT "FK_9eee27210e398202f286bf15cf4"`);
        await queryRunner.query(`ALTER TABLE "offering" DROP CONSTRAINT "FK_bc5b058bcf48bea21f3d172e61d"`);
        await queryRunner.query(`ALTER TABLE "offering" DROP CONSTRAINT "FK_82eda015612fcb170f436545feb"`);
        await queryRunner.query(`ALTER TABLE "value_stream" DROP CONSTRAINT "FK_c22e3336d8df877dda668a93e8a"`);
        await queryRunner.query(`ALTER TABLE "value_stream" DROP CONSTRAINT "FK_d37e3ffc041d9217905fa5d28ba"`);
        await queryRunner.query(`ALTER TABLE "password_reset_token" DROP CONSTRAINT "FK_a4e53583f7a8ab7d01cded46a41"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_0d423777b801a88f0709c6be43e"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_a57aed940fb25c422f2774cd2b3"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_b61c694cacfab25533bd23d9add"`);
        await queryRunner.query(`ALTER TABLE "user" DROP CONSTRAINT "FK_643734a7916743c1b226b9b1b32"`);
        await queryRunner.query(`ALTER TABLE "agreement" DROP CONSTRAINT "FK_5354036afbc0e8c80bca5a39539"`);
        await queryRunner.query(`ALTER TABLE "agreement" DROP CONSTRAINT "FK_b405575b2b53872d540f0487a63"`);
        await queryRunner.query(`ALTER TABLE "file_upload" DROP CONSTRAINT "FK_e518fe539e9b5ea0b0b35ffc82d"`);
        await queryRunner.query(`ALTER TABLE "folder" DROP CONSTRAINT "FK_9ee3bd0f189fb242d488c0dfa39"`);
        await queryRunner.query(`ALTER TABLE "agreement_party" DROP CONSTRAINT "FK_5a75d372f3374aaea73bd1e3de4"`);
        await queryRunner.query(`ALTER TABLE "agreement_party" DROP CONSTRAINT "FK_6b1da075588819a6e5665188291"`);
        await queryRunner.query(`ALTER TABLE "agent" DROP CONSTRAINT "FK_92b8f3a4e5b1aaf7a8128e756a7"`);
        await queryRunner.query(`ALTER TABLE "geography" DROP CONSTRAINT "FK_c67d70f484f1194d3586bbdcdcb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e5a503e5cbbd62cc42c05b3dfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3689646ea3533fa4b584a2185c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_634acfdbad4946b437dc1d3d65"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cc76bd69d7789dd4ecb61db95b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe732379b449e3dc89f52b8b44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_073b49e13e4ebe5c294443a16b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d17903383ecacdb7a39ab91a79"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7465429748c191ae44d8421269"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5ccf08bee106a423fcce33feec"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1d0e4175c4251853024c24ff3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_324e592c57094c9dcfa00ddf91"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a4e53583f7a8ab7d01cded46a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b61c694cacfab25533bd23d9ad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e12875dfb3b1d92d7d7c5377e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03f3269461e7b003dca6b1699f"`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "UQ_user_agentId" UNIQUE ("agentId")`);
        await queryRunner.query(`CREATE TYPE "public"."file_storage_provider_enum_old" AS ENUM('local', 's3')`);
        await queryRunner.query(`ALTER TABLE "file_upload" ALTER COLUMN "storageProvider" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_upload" ALTER COLUMN "storageProvider" TYPE "public"."file_storage_provider_enum_old" USING "storageProvider"::"text"::"public"."file_storage_provider_enum_old"`);
        await queryRunner.query(`ALTER TABLE "file_upload" ALTER COLUMN "storageProvider" SET DEFAULT 'local'`);
        await queryRunner.query(`DROP TYPE "public"."file_upload_storageprovider_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."file_storage_provider_enum_old" RENAME TO "file_storage_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "value_files" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "value_files" ADD "position" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d17eb0772114ff72a7ed58d9d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_531bb15cc3c53b256ba573ac05"`);
        await queryRunner.query(`DROP TABLE "offering_files"`);
        await queryRunner.query(`DROP TABLE "offering_item"`);
        await queryRunner.query(`DROP TABLE "offering"`);
        await queryRunner.query(`DROP TYPE "public"."offering_state_enum"`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" ADD CONSTRAINT "CHK_ledger_transaction_different_accounts" CHECK (("fromAccountId" <> "toAccountId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_channel_closure_descendant" ON "channel_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_channel_closure_ancestor" ON "channel_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_agreement_closure_descendant" ON "agreement_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_agreement_closure_ancestor" ON "agreement_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_folder_closure_descendant" ON "folder_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_folder_closure_ancestor" ON "folder_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_geography_closure_descendant" ON "geography_closure" ("id_descendant") `);
        await queryRunner.query(`CREATE INDEX "IDX_geography_closure_ancestor" ON "geography_closure" ("id_ancestor") `);
        await queryRunner.query(`CREATE INDEX "IDX_value_files_fileId" ON "value_files" ("fileId") `);
        await queryRunner.query(`CREATE INDEX "IDX_value_files_valueId" ON "value_files" ("valueId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ledger_transaction_verified" ON "ledger_transaction" ("verified") `);
        await queryRunner.query(`CREATE INDEX "IDX_ledger_transaction_timestamp" ON "ledger_transaction" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "IDX_ledger_transaction_toAccountId" ON "ledger_transaction" ("toAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_ledger_transaction_fromAccountId" ON "ledger_transaction" ("fromAccountId") `);
        await queryRunner.query(`CREATE INDEX "IDX_account_valueId" ON "account" ("valueId") `);
        await queryRunner.query(`CREATE INDEX "IDX_account_ownerAgentId" ON "account" ("ownerAgentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_password_reset_token_tokenHash" ON "password_reset_token" ("tokenHash") `);
        await queryRunner.query(`CREATE INDEX "IDX_password_reset_token_userId" ON "password_reset_token" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_agentId" ON "user" ("agentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_email" ON "user" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_file_upload_folder" ON "file_upload" ("folderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_agreement_party_agent" ON "agreement_party" ("agentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_agreement_party_agreement" ON "agreement_party" ("agreementId") `);
        await queryRunner.query(`CREATE INDEX "IDX_locale_code" ON "locale" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_geography" ON "agent" ("geographyId") `);
        await queryRunner.query(`CREATE INDEX "IDX_agent_coordinates" ON "agent" ("latitude", "longitude") WHERE ((latitude IS NOT NULL) AND (longitude IS NOT NULL))`);
        await queryRunner.query(`CREATE INDEX "IDX_geography_code_parent" ON "geography" ("code", "parentId") `);
        await queryRunner.query(`ALTER TABLE "channel_closure" ADD CONSTRAINT "FK_channel_closure_descendant" FOREIGN KEY ("id_descendant") REFERENCES "channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel_closure" ADD CONSTRAINT "FK_channel_closure_ancestor" FOREIGN KEY ("id_ancestor") REFERENCES "channel"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" ADD CONSTRAINT "FK_agreement_closure_descendant" FOREIGN KEY ("id_descendant") REFERENCES "agreement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_closure" ADD CONSTRAINT "FK_agreement_closure_ancestor" FOREIGN KEY ("id_ancestor") REFERENCES "agreement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folder_closure" ADD CONSTRAINT "FK_folder_closure_descendant" FOREIGN KEY ("id_descendant") REFERENCES "folder"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folder_closure" ADD CONSTRAINT "FK_folder_closure_ancestor" FOREIGN KEY ("id_ancestor") REFERENCES "folder"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geography_closure" ADD CONSTRAINT "FK_geography_closure_descendant" FOREIGN KEY ("id_descendant") REFERENCES "geography"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geography_closure" ADD CONSTRAINT "FK_geography_closure_ancestor" FOREIGN KEY ("id_ancestor") REFERENCES "geography"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_files" ADD CONSTRAINT "FK_value_files_file" FOREIGN KEY ("fileId") REFERENCES "file_upload"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_files" ADD CONSTRAINT "FK_value_files_value" FOREIGN KEY ("valueId") REFERENCES "value"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxonomy" ADD CONSTRAINT "FK_taxonomy_image" FOREIGN KEY ("imageId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taxonomy" ADD CONSTRAINT "FK_4fb69b794e4809058d4ca3a2e57" FOREIGN KEY ("parentId") REFERENCES "taxonomy"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "channel" ADD CONSTRAINT "FK_channel_parent" FOREIGN KEY ("parentId") REFERENCES "channel"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" ADD CONSTRAINT "FK_ledger_transaction_toAccount" FOREIGN KEY ("toAccountId") REFERENCES "account"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ledger_transaction" ADD CONSTRAINT "FK_ledger_transaction_fromAccount" FOREIGN KEY ("fromAccountId") REFERENCES "account"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_account_value" FOREIGN KEY ("valueId") REFERENCES "value"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account" ADD CONSTRAINT "FK_account_ownerAgent" FOREIGN KEY ("ownerAgentId") REFERENCES "agent"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_stream" ADD CONSTRAINT "FK_value_stream_image" FOREIGN KEY ("imageId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "value_stream" ADD CONSTRAINT "FK_c22e3336d8df877dda668a93e8a" FOREIGN KEY ("parentId") REFERENCES "value_stream"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_token" ADD CONSTRAINT "FK_password_reset_token_user" FOREIGN KEY ("userId") REFERENCES "user"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_defaultLocale" FOREIGN KEY ("defaultLocaleId") REFERENCES "locale"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_relationshipAgreement" FOREIGN KEY ("relationshipAgreementId") REFERENCES "agreement"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_agent" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ADD CONSTRAINT "FK_user_avatarFile" FOREIGN KEY ("avatarFileId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement" ADD CONSTRAINT "FK_agreement_file" FOREIGN KEY ("fileId") REFERENCES "file_upload"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement" ADD CONSTRAINT "FK_agreement_parent" FOREIGN KEY ("parentId") REFERENCES "agreement"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_upload" ADD CONSTRAINT "FK_file_upload_folder" FOREIGN KEY ("folderId") REFERENCES "folder"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "folder" ADD CONSTRAINT "FK_folder_parent" FOREIGN KEY ("parentId") REFERENCES "folder"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_party" ADD CONSTRAINT "FK_agreement_party_agent" FOREIGN KEY ("agentId") REFERENCES "agent"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agreement_party" ADD CONSTRAINT "FK_agreement_party_agreement" FOREIGN KEY ("agreementId") REFERENCES "agreement"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "agent" ADD CONSTRAINT "FK_agent_geography" FOREIGN KEY ("geographyId") REFERENCES "geography"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "geography" ADD CONSTRAINT "FK_geography_parent" FOREIGN KEY ("parentId") REFERENCES "geography"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
