export enum TableName {
  VALUES = 'values',
  VALUE_INSTANCES = 'value_instances',
  VALUE_STREAMS = 'value_streams',
  ACTORS = 'actors',
  USERS = 'users',
  ACCOUNTS = 'accounts',
  TRANSACTIONS = 'transactions',
  OFFERINGS = 'offerings',
  EXCHANGES = 'exchanges',
  CHANNELS = 'channels',
  INVOICES = 'invoices',
  AGREEMENTS = 'agreements',
  GEOGRAPHIES = 'geographies',
  TENSIONS = 'tensions',
  PIPELINES = 'pipelines',
  ARCHETYPES = 'archetypes',
  ORDERS = 'orders',
  AGREEMENT_TEMPLATES = 'agreement_templates',
}
